[twitch]
username = "drballsphd"
channel = ""
server = "irc.chat.twitch.tv"
token = "oauth:pa208qgqd3ekohfolj3z6m4odzyk7s"

[terminal]
delay = 30
maximum_messages = 500
verbose = false
first_state = "Dashboard"

[storage]
channels = false
mentions = false

[filters]
enabled = false
reversed = false

[frontend]
show_datetimes = true
datetime_format = "%a %b %e %T %Y"
username_shown = true
palette = "pastel"
title_shown = true
margin = 0
badges = false
theme = "dark"
username_highlight = true
state_tabs = false
cursor_shape = "user"
blinking_cursor = false
inverted_scrolling = false
show_scroll_offset = false
twitch_emotes = true
betterttv_emotes = true
seventv_emotes = true
frankerfacez_emotes = true
favorite_channels = []
recent_channel_count = 5
border_type = "plain"
right_align_usernames = false
